### ISSUE TITLE
ability to disable touch screen

### ISSUE THREAD

**Issue by abdullahjanem** [alex-spataru/HP-Spectre-4101dx-Hackintosh#6]
when I close the lid the touch screen registers input from touching the keyboard, and I have seen some people saying that it may have high power consumption, so I was wondering if you know a way I can disable the touch screen entirely, thanks in advance.

**Comment by eraycn** [comment]
If you dont use VoodooI2C kexts, it is already disabled, also remove the entries related to these kexts from your config.plist

**Comment by abdullahjanem** [comment]
i removed all Voodool2C kexts and removed their entries from config.plist, but now I get stuck in an apple logo boot screen, I am sorry I am super new to this, I just copied ur efi folder and installed mac without changing anything, is there an easy way i can disable touch input? do u mind making an efi folder that lacks touch kexts?

**Comment by alex-spataru** [comment]
Hi @abdullahjanem, I don´t recommend removing all the VoodooI2C kexts because the touchpad may stop working correctly. To disable touchscreen support, just remove `VoodooI2CHID.kext` and update your `config.plist' file with [ProperTree](https://github.com/corpnewt/ProperTree). You can also check the [Dortania OpenCore guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/), it contains a lot of useful information regarding OpenCore & Hackintoshes in general. Please let me know if the proposed solution worked for you.

**Comment by abdullahjanem** [comment]
that worked, thanks I really appreciate your work, one last thing, the Bluetooth range is very small is there a way I can fix that? , I have an intel 7265NGW wifi card. I tried swapping the card with another one with the same model number and the problem is still there. my AirPods disconnect if they are not 20cm close to the laptop. thanks again for your work.

**Comment by alex-spataru** [comment]
I have moved the bluetooth issue to discussions. Honestly, I almost don't use Bluetooth because I prefer to listen with auxiliary earphones. I will try to test Bt and see what can be done about it.
